algobox_admin/controllers/BatchController.php
<?php

namespace app\controllers;

use app\models\Course;
use app\models\UsersSearch;
use Yii;
use app\models\Batch;
use app\models\Batchcontent;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BatchController implements the CRUD actions for Batch model.
 */
class BatchController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }


    /**
     * Lists all Batch models.
     * @return mixed
     */

    public function actionIndex($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Batch::find()->andFilterWhere(['course_id' =>$id]),
        ]);

        $courseModel=Course::findOne($id);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'id' => $id,
            'courseModel' => $courseModel
        ]);
    }

    public function actionUserbatch($id)
    {
        if (isset($_GET['pageSize'])) {
            Yii::$app->session->set('usersPageSize', (int) $_GET['pageSize']);
            unset($_GET['pageSize']);
        }

        $batchModel=\app\models\Batch::findOne($id);
        $assignUserData='';
        if ($batchModel){
            $assignUserData=(array)json_decode($batchModel->assign_users);
        }
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->searchAssigUser(Yii::$app->request->queryParams,$assignUserData);

        return $this->render('userbatch', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Batch model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Batchcontent::find()->andFilterWhere(['batch_id' =>$id]),
            
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id), 'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Batch model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Batch();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->batch_id]);
        }

        $model->date = date("Y-m-d H:i:s",time());
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Batch model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->batch_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionUpdateAssignUsers($id='')
    {
        $post = Yii::$app->request->post();

        if ($post){
            $batchId=$post['batchIdValue'];
            $selectionsData=$post['selection'];
            $gettingBatchModel=Batch::findOne($batchId);
            $gettingBatchModel->assign_users=json_encode($selectionsData);
                if ($gettingBatchModel->save()){
                    echo 1;
                    exit();
                }else{
                    echo 2;
                    exit();
                }
        }
    }

    /**
     * Deletes an existing Batch model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id,$courseId='')
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index','id'=>$courseId]);
    }

    /**
     * Finds the Batch model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Batch the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Batch::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

algobox_admin/controllers/BatchcontentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Batchcontent;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BatchcontentController implements the CRUD actions for Batchcontent model.
 */
class BatchcontentController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Batchcontent models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Batchcontent::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Batchcontent model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Batchcontent model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Batchcontent();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['batch/view', 'id' => $model->batch_id]);
        }

        $model->batch_id = $id;
        $model->start_time = date("Y-m-d H:i:s",time());
        $model->end_time = date("Y-m-d H:i:s",time());
        return $this->render('create', [
            'model' => $model, 'id' => $id,
        ]);

    }

    /**
     * Updates an existing Batchcontent model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['batch/view', 'id' => $model->batch_id]);
        }

        return $this->render('update', [
            'model' => $model,'id' =>$id,
        ]);
    }

    /**
     * Deletes an existing Batchcontent model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Batchcontent model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Batchcontent the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Batchcontent::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

algobox_admin/controllers/CourseController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Course;
use app\models\Coursecontent;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CourseController implements the CRUD actions for Course model.
 */
class CourseController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Course models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Course::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Course model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Coursecontent::find()->andFilterWhere(['course_id' =>$id,])
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id), 'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Course model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Course();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->course_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);

    }

    /**
     * Updates an existing Course model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->course_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Course model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Course model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Course the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Course::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

algobox_admin/controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\MappingPackage;
use Yii;
use yii\filters\AccessControl;
use app\models\Users;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\UsersSearch;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','create','update','view'],
                'rules' => [
                    [
                        'actions' => ['index','create','update','view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (isset($_GET['pageSize'])) {
            Yii::$app->session->set('usersPageSize', (int) $_GET['pageSize']);
			unset($_GET['pageSize']);
        }

        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $post=Yii::$app->request->post();
        $variationsPackage=Yii::$app->request->post();
        $model = new Users();
        unset($post['Package']);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                if ($variationsPackage) {
                    foreach ($variationsPackage['Package'] as $key => $value) {
                        $expireDate = !empty($value['expire_date']) ? $value['expire_date'] : '';
                        $packagename = !empty($value['name']) ? $value['name'] : '';
                        $mapingPackageModel = new MappingPackage();
                        $mapingPackageModel->user_id = $model->UserID;
                        $mapingPackageModel->package_name = $packagename;
                        $mapingPackageModel->expire = date("Y-m-d", strtotime($expireDate));
                        $mapingPackageModel->save();
                    }
                }
            }
            return $this->redirect(['view', 'id' => $model->UserID]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $post=Yii::$app->request->post();
        $variationsPackage=Yii::$app->request->post();
        $model = $this->findModel($id);
        unset($post['Package']);

//        echo "<pre>";
//        print_r($post);
//        exit();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()){
                MappingPackage::deleteAll(['user_id' => $model->UserID]);
                if ($variationsPackage) {
                    foreach ($variationsPackage['Package'] as $key => $value) {
                        $expireDate = !empty($value['expire_date']) ? $value['expire_date'] : '';
                        $packagename = !empty($value['name']) ? $value['name'] : '';
                        $mapingPackageModel = new MappingPackage();
                        $mapingPackageModel->user_id = $model->UserID;
                        $mapingPackageModel->package_name = $packagename;
                        $mapingPackageModel->expire = date("Y-m-d", strtotime($expireDate));
                        $mapingPackageModel->save();
                    }
                }
            }
            return $this->redirect(['view', 'id' => $model->UserID]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

algobox_admin/views/batch/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;


/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$courseName=$courseId='';
if ($courseModel){
    $courseName=$courseModel->course_name;
    $courseId=$courseModel->course_id;
}
$this->title = 'Batches';
$this->params['breadcrumbs'][] = ['label' =>'Courses', 'url' => ['course/index']];
$this->params['breadcrumbs'][] =['label' =>$courseName, 'url' => ['course/view/', 'id' => $courseId]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="batch-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Batch', ['create','id'=>$id], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'batch_id',
            ['attribute' => 'batch_name', 
             'headerOptions' => ['width' => '200px'],
             'format' => 'raw', 
             'value' => function ($model) {
                return Html::a($model->batch_name,['batch/view', 'id'=>$model->batch_id,'courseId' => $model->course_id]);
            }],
            //'batch_no',
            ['attribute' => 'date', 
             'format' => 'raw',
             'value' => function($model){return $model->date;}
            ],
            
            [
                'attribute' => 'active',
                'value' => function ($model) {
                    return $model->active ? "Yes" : "No";
                },
                'contentOptions' => function ($model, $key, $index, $column) { 
                    return $model->active ? ['style' => 'color:green'] : ['style' => 'color:red']; 
                }
            ],
            'description',
            'course_id',
            //'lastupdate',
            ['class' => 'yii\grid\ActionColumn',

                'contentOptions' => ['class' => 'text-center'],
                'buttons' => [
                    'view' => function ($url,$model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>',['batch/view', 'id' => $model->batch_id]);
                    },
                    'update' => function ($url,$model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>',['batch/update', 'id' => $model->batch_id]);
                    },
                    'delete' => function ($url,$model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>',['batch/delete', 'id' => $model->batch_id,'courseId' => $_REQUEST['id']],
                            ['data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                            ]);
                    },
                ]],
        ],
    ]); ?>


</div>

algobox_admin/views/batch/userbatch.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$batchId=isset($_REQUEST['id'])?$_REQUEST['id']:'';

$batchModel=\app\models\Batch::findOne($batchId);
$courseName=$courseId=$batchName='';
if ($batchModel){
    $batchName=$batchModel->batch_name;
    $courseModel=\app\models\Course::findOne($batchModel->course_id);
    if ($courseModel){
        $courseName=$courseModel->course_name;
        $courseId=$courseModel->course_id;
    }
}

$this->title = 'Users';
$this->params['breadcrumbs'][] = ['label' =>'Courses', 'url' => ['course/index']];
$this->params['breadcrumbs'][] = ['label' => $courseName, 'url' => ['course/view', 'id' => $courseId]];
$this->params['breadcrumbs'][] = ['label' => 'Batches', 'url' => ['batch/index','id'=>$courseId]];
$this->params['breadcrumbs'][] = ['label' => $batchName, 'url' => ['batch/view','id'=>$batchId]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-index">

    <h1><?= Html::encode($this->title) .' : '.$batchName ?></h1>

    <p>
        <?= Html::a('Assign user into batch', ['users/index', 'batchId' => $batchId], ['class' => 'btn btn-success']) ?>
    </p>

    <?php
    //$role = Yii::$app->session->get('user.role');
    $role = Users::findOne(Yii::$app->user->id)->UserRole;
    $pageSize=Yii::$app->session->get('usersPageSize',Yii::$app->params['listPerPage']);
    ?>

    <?php
    if (/*$role >= Yii::$app->params['superuser'] || */$role >= Yii::$app->params['administrator']) {
        $template = '{view}{update}{delete}';
        $rTemplate = [Yii::$app->params['superuser'] => 'Superuser',
            Yii::$app->params['administrator'] => 'Admin',
            Yii::$app->params['supervisor'] => 'Supervisor',
            Yii::$app->params['operatortester'] => 'Operator Tester',
            Yii::$app->params['research'] => 'Research',
            Yii::$app->params['operator'] => 'Operator'];
    }/* else if ($role == Yii::$app->params['manager']) {
        $template = '{view}{update}';
        $rTemplate = [Yii::$app->params['manager'] => 'Manager',
                    Yii::$app->params['leader'] => 'BA',
                    Yii::$app->params['agent'] => 'Agent'];
    }*/ else if ($role >= Yii::$app->params['operator']){
        $template = '{view}';
        $rTemplate = [];
    } else {
        $template = '';
        $rTemplate = [];
    }
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'filterSelector' => '#pageSize',
        'emptyCell'=>'-',
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            'UserID',
            //'UserID2',
            //'UserPWD',
            //'UserKey',
            ['attribute' => 'UserName',
                'format' => 'raw',
                'value' => function($model){return !$model->UserName ? Yii::$app->formatter->nullDisplay : $model->UserName.'<BR><small>'.
                    (!$model->Email ? Yii::$app->formatter->nullDisplay : $model->Email).'</small>';},
                'headerOptions' => ['style'=>'min-width: 180px;']
            ],
            'LastLogin',
//            ['attribute' => 'Package',
//                'label' => 'Package 1',
//                'format' => 'raw',
//                'value' => function($model){return !$model->Package ? Yii::$app->formatter->nullDisplay : $model->Package.'<BR><small>Exp: '.
//                    (!$model->UserExpiryDate ? Yii::$app->formatter->nullDisplay : $model->UserExpiryDate).'</small>';}
//            ],
//            ['attribute' => 'Package2',
//                'label' => 'Package 2',
//                'format' => 'raw',
//                'value' => function($model){return !$model->Package2 ? Yii::$app->formatter->nullDisplay : $model->Package2.'<BR><small>Exp: '.
//                    (!$model->expiry2 ? Yii::$app->formatter->nullDisplay : $model->expiry2).'</small>';}
//            ],
            ['attribute' => 'Build', 'headerOptions' => ['style'=>'width: 70px;']],
            ['attribute' => 'referral_code', 'label' => 'Ref. Code'],
            //'UserExpiryDate',
            //'pre_mco_expiry',
            //'pre_mco_expiry_vf',
            //'last_expiry',
            //'UserLastUpdatedDate',
            //'UserNextRegistrationDate',
            //'SerialKey',
            //'SerialKeyM',
            //'SerialKeyV',
            //'UserRole',
            //'Admin',
            //'referral_code',
            'agent_id',
            //'Device',
            //'SessionID',
            //'LastLogin2',
            //'Device2',
            //'SessionID2',
            //'WebSession',
            //'Email:email',
            //'Phone',
            //'IC',
            //'Address',
            //'Country',
            //'Package',
            //'Package2',
            //'expiry2',
            //'last_expiry2',
            //'Package3',
            //'expiry3',
            //'Build',
            //'Versions:ntext',
            //'DeviceToken',
            //'dob',
            //'gender',
            //'age_group',
            //'invest_exp',
            //'special1',
            //'special2',
            //'special3',
            //'years1',
            //'years2',
            //'years3',
            //'sector1',
            //'sector2',
            //'sector3',
            //'sector4',
            //'hide_profile',
            //'profile_update',
            //'profile_status',
            'create_date',
            //'self_create_date',
            //'payment',
            //'payment2',
            //'remark',
            //'mtp_group',
            //'auth_key',
        ],
    ]); ?>


</div>

<style>
    /*.thead-blue table thead {
        background-color: cornflowerblue;
    }
    .grid-view table thead {
        background-color: #cccccc;
    }

    .grid-view table thead a {
        color: #2e2eb8;
    }*/

    .grid-view table tr:hover {
        background-color: #E9E9E9;
    }

    .table-striped {
        background-color: #F5F5F5;
    }

    .grid-view table tr td {
        padding: 5px;
    }
</style>

algobox_admin/views/batch/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Batch */

$courseModel=\app\models\Course::findOne($model->course_id);
$courseName=$courseId='';
if ($courseModel){
    $courseName=$courseModel->course_name;
}

$this->title = $model->batch_name;
$this->params['breadcrumbs'][] = ['label' =>'Courses', 'url' => ['course/index']];
$this->params['breadcrumbs'][] = ['label' => $courseName, 'url' => ['course/view', 'id' => $model->course_id]];
$this->params['breadcrumbs'][] = ['label' => 'Batches', 'url' => ['batch/index','id'=>$model->course_id]];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="batch-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('<< Back', ['batch/index','id'=>$model->course_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Update', ['update', 'id' => $model->batch_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->batch_id,'courseId'=>$model->course_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('User batch', ['batch/userbatch', 'id' => $model->batch_id], ['class' => 'btn btn-success']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'batch_id',
            'batch_name',
            //'batch_no',
            'date',
            ['attribute' => 'active',
            'value' => function ($model) {
                return $model->active ? "Yes" : "No";
            },
            'contentOptions' => ['style' => $model->active ? 'color:green' :'color:red']],
            'description',
            ['attribute' => 'package',
                'label' => 'Package',
                'format' => 'raw',
                'value' => function($model){return !$model->package ? Yii::$app->formatter->nullDisplay : $model->package.'<BR><small>Exp: '.
                    (!$model->expiry ? Yii::$app->formatter->nullDisplay : $model->expiry).'</small>';}
            ],
            //'course_id',
            //'lastupdate',
        ],
    ]) ?>

    <h2>Timetable</h2>

    <p>
        <?= Html::a('Create Batch content', ['batchcontent/create', 'id' => $model->batch_id], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'batchcontent_id',
            ['attribute' => 'coursecontent_id',
                'label' => 'Chapter Name',
                'value' => function ($model) {
                    $getChapterNameFromCourseContent=\app\models\Coursecontent::findOne($model->coursecontent_id);
                    if ($getChapterNameFromCourseContent){
                        return $getChapterNameFromCourseContent->chapter_name;
                    }else{
                        return "";
                    }
                },
            ],
            'description',
            'start_time',
            'end_time',
            'video_link',
            ['attribute' => 'active',
                'value' => function ($model) {
                    return $model->active ? "Yes" : "No";
                },
                'contentOptions' => function ($model, $key, $index, $column) { 
                    return $model->active ? ['style' => 'color:green'] : ['style' => 'color:red']; 
            }],
            //'seq',
            //'batch_id',

            ['class' => 'yii\grid\ActionColumn',
             
             'contentOptions' => ['class' => 'text-center'],
             'buttons' => [
                'view' => function ($url,$model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>',['batchcontent/view', 'id' => $model->batchcontent_id]);
                },
                'update' => function ($url,$model) {
                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>',['batchcontent/update', 'id' => $model->batchcontent_id]);
                },
                'delete' => function ($url,$model) {
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>',['batchcontent/delete', 'id' => $model->batchcontent_id],
                        ['data' => [
                            'confirm' => 'Are you sure you want to delete this item?',
                            'method' => 'post',
                        ],
                    ]);
                },
            ]],
        ],
    ]); ?>

</div>