algobox_admin/controllers/BatchController.php
<?php

namespace app\controllers;

use app\models\Course;
use app\models\UsersSearch;
use Yii;
use app\models\Batch;
use app\models\Batchcontent;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BatchController implements the CRUD actions for Batch model.
 */
class BatchController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }


    /**
     * Lists all Batch models.
     * @return mixed
     */

    public function actionIndex($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Batch::find()->andFilterWhere(['course_id' =>$id]),
        ]);

        $courseModel=Course::findOne($id);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'id' => $id,
            'courseModel' => $courseModel
        ]);
    }

    public function actionUserbatch($id)
    {
        if (isset($_GET['pageSize'])) {
            Yii::$app->session->set('usersPageSize', (int) $_GET['pageSize']);
            unset($_GET['pageSize']);
        }

        $batchModel=\app\models\Batch::findOne($id);
        $assignUserData='';
        if ($batchModel){
            $assignUserData=(array)json_decode($batchModel->assign_users);
        }
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->searchAssigUser(Yii::$app->request->queryParams,$assignUserData);

        return $this->render('userbatch', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Batch model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Batchcontent::find()->andFilterWhere(['batch_id' =>$id]),
            
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id), 'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Batch model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Batch();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->batch_id]);
        }

        $model->date = date("Y-m-d H:i:s",time());
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Batch model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->batch_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionUpdateAssignUsers($id='')
    {
        $post = Yii::$app->request->post();

        if ($post){
            $batchId=$post['batchIdValue'];
            $selectionsData=$post['selection'];
            $gettingBatchModel=Batch::findOne($batchId);
            $gettingBatchModel->assign_users=json_encode($selectionsData);
                if ($gettingBatchModel->save()){
                    echo 1;
                    exit();
                }else{
                    echo 2;
                    exit();
                }
        }
    }

    /**
     * Deletes an existing Batch model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id,$courseId='')
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index','id'=>$courseId]);
    }

    /**
     * Finds the Batch model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Batch the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Batch::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

algobox_admin/controllers/CourseController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Course;
use app\models\Coursecontent;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CourseController implements the CRUD actions for Course model.
 */
class CourseController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Course models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Course::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Course model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Coursecontent::find()->andFilterWhere(['course_id' =>$id,])
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id), 'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Course model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Course();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->course_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);

    }

    /**
     * Updates an existing Course model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->course_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Course model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Course model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Course the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Course::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

algobox_admin/controllers/UsersController.php
<?php

namespace app\controllers;

use app\models\MappingPackage;
use Yii;
use yii\filters\AccessControl;
use app\models\Users;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\UsersSearch;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','create','update','view'],
                'rules' => [
                    [
                        'actions' => ['index','create','update','view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (isset($_GET['pageSize'])) {
            Yii::$app->session->set('usersPageSize', (int) $_GET['pageSize']);
			unset($_GET['pageSize']);
        }

        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $post=Yii::$app->request->post();
        $variationsPackage=Yii::$app->request->post();
        $model = new Users();
        unset($post['Package']);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                if ($variationsPackage) {
                    foreach ($variationsPackage['Package'] as $key => $value) {
                        $expireDate = !empty($value['expire_date']) ? $value['expire_date'] : '';
                        $packagename = !empty($value['name']) ? $value['name'] : '';
                        $mapingPackageModel = new MappingPackage();
                        $mapingPackageModel->user_id = $model->UserID;
                        $mapingPackageModel->package_name = $packagename;
                        $mapingPackageModel->expire = date("Y-m-d", strtotime($expireDate));
                        $mapingPackageModel->save();
                    }
                }
            }
            return $this->redirect(['view', 'id' => $model->UserID]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $post=Yii::$app->request->post();
        $variationsPackage=Yii::$app->request->post();
        $model = $this->findModel($id);
        unset($post['Package']);

//        echo "<pre>";
//        print_r($post);
//        exit();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()){
                MappingPackage::deleteAll(['user_id' => $model->UserID]);
                if ($variationsPackage) {
                    foreach ($variationsPackage['Package'] as $key => $value) {
                        $expireDate = !empty($value['expire_date']) ? $value['expire_date'] : '';
                        $packagename = !empty($value['name']) ? $value['name'] : '';
                        $mapingPackageModel = new MappingPackage();
                        $mapingPackageModel->user_id = $model->UserID;
                        $mapingPackageModel->package_name = $packagename;
                        $mapingPackageModel->expire = date("Y-m-d", strtotime($expireDate));
                        $mapingPackageModel->save();
                    }
                }
            }
            return $this->redirect(['view', 'id' => $model->UserID]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

algobox_admin/views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UsersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'UserID') ?>

    <?= $form->field($model, 'UserID2') ?>

    <?= $form->field($model, 'UserPWD') ?>

    <?= $form->field($model, 'UserKey') ?>

    <?= $form->field($model, 'UserName') ?>

    <?php // echo $form->field($model, 'UserExpiryDate') ?>

    <?php // echo $form->field($model, 'pre_mco_expiry') ?>

    <?php // echo $form->field($model, 'pre_mco_expiry_vf') ?>

    <?php // echo $form->field($model, 'last_expiry') ?>

    <?php // echo $form->field($model, 'UserLastUpdatedDate') ?>

    <?php // echo $form->field($model, 'UserNextRegistrationDate') ?>

    <?php // echo $form->field($model, 'SerialKey') ?>

    <?php // echo $form->field($model, 'SerialKeyM') ?>

    <?php // echo $form->field($model, 'SerialKeyV') ?>

    <?php // echo $form->field($model, 'UserRole') ?>

    <?php // echo $form->field($model, 'Admin') ?>

    <?php // echo $form->field($model, 'referral_code') ?>

    <?php // echo $form->field($model, 'agent_id') ?>

    <?php // echo $form->field($model, 'LastLogin') ?>

    <?php // echo $form->field($model, 'Device') ?>

    <?php // echo $form->field($model, 'SessionID') ?>

    <?php // echo $form->field($model, 'LastLogin2') ?>

    <?php // echo $form->field($model, 'Device2') ?>

    <?php // echo $form->field($model, 'SessionID2') ?>

    <?php // echo $form->field($model, 'WebSession') ?>

    <?php // echo $form->field($model, 'Email') ?>

    <?php // echo $form->field($model, 'Phone') ?>

    <?php // echo $form->field($model, 'IC') ?>

    <?php // echo $form->field($model, 'Address') ?>

    <?php // echo $form->field($model, 'Country') ?>

    <?php // echo $form->field($model, 'Package') ?>

    <?php // echo $form->field($model, 'Package2') ?>

    <?php // echo $form->field($model, 'expiry2') ?>

    <?php // echo $form->field($model, 'last_expiry2') ?>

    <?php // echo $form->field($model, 'Package3') ?>

    <?php // echo $form->field($model, 'expiry3') ?>

    <?php // echo $form->field($model, 'Build') ?>

    <?php // echo $form->field($model, 'Versions') ?>

    <?php // echo $form->field($model, 'DeviceToken') ?>

    <?php // echo $form->field($model, 'dob') ?>

    <?php // echo $form->field($model, 'gender') ?>

    <?php // echo $form->field($model, 'age_group') ?>

    <?php // echo $form->field($model, 'invest_exp') ?>

    <?php // echo $form->field($model, 'special1') ?>

    <?php // echo $form->field($model, 'special2') ?>

    <?php // echo $form->field($model, 'special3') ?>

    <?php // echo $form->field($model, 'years1') ?>

    <?php // echo $form->field($model, 'years2') ?>

    <?php // echo $form->field($model, 'years3') ?>

    <?php // echo $form->field($model, 'sector1') ?>

    <?php // echo $form->field($model, 'sector2') ?>

    <?php // echo $form->field($model, 'sector3') ?>

    <?php // echo $form->field($model, 'sector4') ?>

    <?php // echo $form->field($model, 'hide_profile') ?>

    <?php // echo $form->field($model, 'profile_update') ?>

    <?php // echo $form->field($model, 'profile_status') ?>

    <?php // echo $form->field($model, 'create_date') ?>

    <?php // echo $form->field($model, 'self_create_date') ?>

    <?php // echo $form->field($model, 'payment') ?>

    <?php // echo $form->field($model, 'payment2') ?>

    <?php // echo $form->field($model, 'remark') ?>

    <?php // echo $form->field($model, 'mtp_group') ?>

    <?php // echo $form->field($model, 'auth_key') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

algobox_admin/views/users/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Create Users';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

algobox_admin/views/users/index.php
<?php

namespace app\models;

use Yii;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$batchId=isset($_REQUEST['batchId'])?$_REQUEST['batchId']:'';
if ($batchId){
    $batchModel=\app\models\Batch::findOne($batchId);
    $courseName=$courseId=$batchName='';
    if ($batchModel){
        $batchName=$batchModel->batch_name;
        $courseModel=\app\models\Course::findOne($batchModel->course_id);
        if ($courseModel){
            $courseName=$courseModel->course_name;
            $courseId=$courseModel->course_id;
        }
    }

    $this->title = 'Users';
    $this->params['breadcrumbs'][] = ['label' =>'Courses', 'url' => ['course/index']];
    $this->params['breadcrumbs'][] = ['label' => $courseName, 'url' => ['course/view', 'id' => $courseId]];
    $this->params['breadcrumbs'][] = ['label' => 'Batches', 'url' => ['batch/index','id'=>$courseId]];
    $this->params['breadcrumbs'][] = ['label' => $batchName, 'url' => ['batch/view','id'=>$batchId]];
    $this->params['breadcrumbs'][] = $this->title;
}else {
    $this->title = 'Users';
    $this->params['breadcrumbs'][] = $this->title;
}

?>
<style>
    p#successMessage {
        font-size: 20px;
    }
</style>
<div class="users-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
        //$role = Yii::$app->session->get('user.role');
        $role = Users::findOne(Yii::$app->user->id)->UserRole;
        $pageSize=Yii::$app->session->get('usersPageSize',Yii::$app->params['listPerPage']);
    ?>

    <p>
        <?php 
            if ($role >= Yii::$app->params['administrator'] && empty($batchId)) {
                echo Html::a('Create Users', ['create'], ['class' => 'btn btn-success']);
            }
            if (!empty($batchId)){ ?>
                <?= Html::a('<< Back', ['batch/userbatch','id'=>$batchId], ['class' => 'btn btn-primary']) ?>
                <button type="button" class="btn btn-success" id="checkAllSaveChange" data-batchId="<?=$batchId?>">Save Change</button>
                <p id="successMessage"></p>
                <input type="hidden" id="batchIdValue" value="<?=$batchId?>">
            <?php }
        ?>
    </p>

    <?php
    if (/*$role >= Yii::$app->params['superuser'] || */$role >= Yii::$app->params['administrator']) {
        $template = '{view}{update}{delete}';
        $rTemplate = [Yii::$app->params['superuser'] => 'Superuser', 
                    Yii::$app->params['administrator'] => 'Admin', 
                    Yii::$app->params['supervisor'] => 'Supervisor',
                    Yii::$app->params['operatortester'] => 'Operator Tester',
                    Yii::$app->params['research'] => 'Research',
                    Yii::$app->params['operator'] => 'Operator'];
    }/* else if ($role == Yii::$app->params['manager']) {
        $template = '{view}{update}';
        $rTemplate = [Yii::$app->params['manager'] => 'Manager',
                    Yii::$app->params['leader'] => 'BA',
                    Yii::$app->params['agent'] => 'Agent'];
    }*/ else if ($role >= Yii::$app->params['operator']){
        $template = '{view}';
        $rTemplate = [];
    } else {
        $template = '';
        $rTemplate = [];
    }
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'filterSelector' => '#pageSize',
        'emptyCell'=>'-',
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            'UserID',
            //'UserID2',
            //'UserPWD',
            //'UserKey',
            ['attribute' => 'UserName', 
            'format' => 'raw',
            'value' => function($model){return !$model->UserName ? Yii::$app->formatter->nullDisplay : $model->UserName.'<BR><small>'.
                                       (!$model->Email ? Yii::$app->formatter->nullDisplay : $model->Email).'</small>';},
             'headerOptions' => ['style'=>'min-width: 180px;']
            ],
            'LastLogin',
//            ['attribute' => 'UserID',
//             'label' => 'Package 1',
//             'format' => 'raw',
//             'value' => function($model) {
//                 $mappingPackageModel = MappingPackage::find()->where(['user_id' => $model->UserID])->orderBy(['id' => SORT_DESC])->one();
//                 if ($mappingPackageModel) {
//                     return !$mappingPackageModel->package_name ? Yii::$app->formatter->nullDisplay : $mappingPackageModel->package_name . '<BR><small>Exp: ' .
//                         (!$mappingPackageModel->expire ? Yii::$app->formatter->nullDisplay : $mappingPackageModel->expire) . '</small>';
//                 } else {
//                     return Yii::$app->formatter->nullDisplay;
//                 }
//             }
//            ],
            ['attribute' => 'Build', 'headerOptions' => ['style'=>'width: 70px;']],
            ['attribute' => 'referral_code', 'label' => 'Ref. Code'],
            //'UserExpiryDate',
            //'pre_mco_expiry',
            //'pre_mco_expiry_vf',
            //'last_expiry',
            //'UserLastUpdatedDate',
            //'UserNextRegistrationDate',
            //'SerialKey',
            //'SerialKeyM',
            //'SerialKeyV',
            //'UserRole',
            //'Admin',
            //'referral_code',
            'agent_id',
            //'Device',
            //'SessionID',
            //'LastLogin2',
            //'Device2',
            //'SessionID2',
            //'WebSession',
            //'Email:email',
            //'Phone',
            //'IC',
            //'Address',
            //'Country',
            //'Package',
            //'Package2',
            //'expiry2',
            //'last_expiry2',
            //'Package3',
            //'expiry3',
            //'Build',
            //'Versions:ntext',
            //'DeviceToken',
            //'dob',
            //'gender',
            //'age_group',
            //'invest_exp',
            //'special1',
            //'special2',
            //'special3',
            //'years1',
            //'years2',
            //'years3',
            //'sector1',
            //'sector2',
            //'sector3',
            //'sector4',
            //'hide_profile',
            //'profile_update',
            //'profile_status',
            'create_date',
            //'self_create_date',
            //'payment',
            //'payment2',
            //'remark',
            //'mtp_group',
            //'auth_key',
            [
                'class' => 'yii\grid\CheckboxColumn',
                'header' => Html::checkBox('fdf', false, [
                    'class' => 'select-on-check-all'
                ]),
                'checkboxOptions' => function($model) {
                    $batchIdRequest=isset($_REQUEST['batchId'])?$_REQUEST['batchId']:'';

                    $checedStatus=false;
                    if ($batchIdRequest){
                        $gettingBatchModel=Batch::findOne($batchIdRequest);
                        $userAssign=(array)json_decode($gettingBatchModel->assign_users);
                        if (in_array($model->UserID, $userAssign)) {
                            $checedStatus=true;
                        }

                    }
                    $userAssingChecked = ["value" => $model->UserID, "class" => 'user-status', "label" => '', "checked" => $checedStatus];
                    return $userAssingChecked;
                },
            ],
            ['class' => 'yii\grid\ActionColumn',
             //'template' => $template,
             'header'=>Html::dropDownList('pageSize', $pageSize, Yii::$app->params['pageSizeOptions'], ['id' => 'pageSize', 'style' => 'margin-top:6px;']),
             'contentOptions' => ['class' => 'text-center'],
            ], 
        ],
    ]); ?>


</div>

<style>
    /*.thead-blue table thead {
        background-color: cornflowerblue;
    }
    .grid-view table thead {
        background-color: #cccccc;
    }

    .grid-view table thead a {
        color: #2e2eb8;
    }*/

    .grid-view table tr:hover {
        background-color: #E9E9E9;
    }

    .table-striped {
        background-color: #F5F5F5;
    }

    .grid-view table tr td {
        padding: 5px;
    }
</style>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    $( document ).ready(function() {
        $('.select-on-check-all').change(function () {
            $('.user-status').prop('checked',this.checked);
        });

        $('.user-status').change(function () {
            if ($('.user-status:checked').length == $('.user-status').length){
                $('#select-on-check-all').prop('checked',true);
            }
            else {
                $('#select-on-check-all').prop('checked',false);
            }
        });

        var checkBatchIdexistOrNot=$('#batchIdValue').val();
        if (checkBatchIdexistOrNot) {
            $('td:nth-child(8)').show();
            $('th:nth-child(8)').show();
            $('td:nth-child(9)').hide();
            $('th:nth-child(9)').hide();
        }else {
            $('td:nth-child(8)').hide();
            $('th:nth-child(8)').hide();
            $('td:nth-child(9)').show();
            $('th:nth-child(9)').show();
        }

        $('#checkAllSaveChange').off('click', '.checkAllSaveChange').on('click',function(e){
            var parsingDataList = [];
            var batchId=$('#batchIdValue').val();
            //Checked Items Push Into List
            $(".user-status:checked").each(function(){
                parsingDataList.push($(this).val());
            });

            if (parsingDataList.length>0) {
                $.ajax({
                    type: 'post',
                    url: '<?php echo Yii::$app->request->baseUrl . '/index.php?r=batch%2Fupdate-assign-users'?>',
                    data: {selection: parsingDataList, batchIdValue: batchId},
                    success: function (response) {
                        if (response == 1) {

                            $('#successMessage').html('Your selected item saved successfully');
                            $('#successMessage').attr("style", "color:green");

                            setTimeout(function () {
                                $('#successMessage').html("");
                            }, 3000);
                        }else {
                            $('#successMessage').html('Something missing try again');
                            $('#successMessage').attr("style", "color:red");
                            setTimeout(function () {
                                $('#successMessage').html("");
                            }, 3000);
                        }
                    }, beforeSend: function (xhr) {
                    },
                });
            }else {
                $('#successMessage').html('Assign at least one');
                $('#successMessage').attr("style", "color:red");
                setTimeout(function () {
                    $('#successMessage').html("");
                }, 3000);
            }
        });
    });
</script>

algobox_admin/views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Update Users: ' . $model->UserID;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->UserID, 'url' => ['view', 'id' => $model->UserID]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="users-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>