algobox_admin/models/Course.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "course".
 *
 * @property int $course_id
 * @property string $course_name
 * @property string|null $description
 * @property int|null $active
 * @property string $lastupdate
 *
 * @property Batch[] $batches
 * @property Coursecontent[] $coursecontents
 * @property Userbatch[] $userbatches
 */
class Course extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'course';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['course_name'], 'required'],
            [['active'], 'integer'],
            [['lastupdate'], 'safe'],
            [['course_name'], 'string', 'max' => 80],
            [['description'], 'string', 'max' => 500],
            [['course_name'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'course_id' => 'Course ID',
            'course_name' => 'Course Name',
            'description' => 'Description',
            'active' => 'Active',
            'lastupdate' => 'Lastupdate',
        ];
    }

    /**
     * Gets query for [[Batches]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getBatches()
    {
        return $this->hasMany(Batch::className(), ['course_id' => 'course_id']);
    }

    /**
     * Gets query for [[Coursecontents]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCoursecontents()
    {
        return $this->hasMany(Coursecontent::className(), ['course_id' => 'course_id']);
    }

    /**
     * Gets query for [[Userbatches]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUserbatches()
    {
        return $this->hasMany(Userbatch::className(), ['course_id' => 'course_id']);
    }

    public function getIsActive() {
        return $this->active == '1' ? 'Yes' : 'No';
    }
}

algobox_admin/controllers/BatchController.php
<?php

namespace app\controllers;

use app\models\Course;
use app\models\UsersSearch;
use Yii;
use app\models\Batch;
use app\models\Batchcontent;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BatchController implements the CRUD actions for Batch model.
 */
class BatchController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }


    /**
     * Lists all Batch models.
     * @return mixed
     */

    public function actionIndex($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Batch::find()->andFilterWhere(['course_id' =>$id]),
        ]);

        $courseModel=Course::findOne($id);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'id' => $id,
            'courseModel' => $courseModel
        ]);
    }

    public function actionUserbatch($id)
    {
        if (isset($_GET['pageSize'])) {
            Yii::$app->session->set('usersPageSize', (int) $_GET['pageSize']);
            unset($_GET['pageSize']);
        }

        $batchModel=\app\models\Batch::findOne($id);
        $assignUserData='';
        if ($batchModel){
            $assignUserData=(array)json_decode($batchModel->assign_users);
        }
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->searchAssigUser(Yii::$app->request->queryParams,$assignUserData);

        return $this->render('userbatch', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single Batch model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Batchcontent::find()->andFilterWhere(['batch_id' =>$id]),
            
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id), 'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Batch model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Batch();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->batch_id]);
        }

        $model->date = date("Y-m-d H:i:s",time());
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Batch model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->batch_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionUpdateAssignUsers($id='')
    {
        $post = Yii::$app->request->post();

        if ($post){
            $batchId=$post['batchIdValue'];
            $selectionsData=$post['selection'];
            $gettingBatchModel=Batch::findOne($batchId);
            $gettingBatchModel->assign_users=json_encode($selectionsData);
                if ($gettingBatchModel->save()){
                    echo 1;
                    exit();
                }else{
                    echo 2;
                    exit();
                }
        }
    }

    /**
     * Deletes an existing Batch model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id,$courseId='')
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index','id'=>$courseId]);
    }

    /**
     * Finds the Batch model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Batch the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Batch::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

algobox_admin/controllers/CourseController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Course;
use app\models\Coursecontent;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CourseController implements the CRUD actions for Course model.
 */
class CourseController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Course models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Course::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Course model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Coursecontent::find()->andFilterWhere(['course_id' =>$id,])
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id), 'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Course model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Course();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->course_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);

    }

    /**
     * Updates an existing Course model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->course_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Course model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Course model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Course the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Course::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

algobox_admin/controllers/CoursecontentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Coursecontent;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CoursecontentController implements the CRUD actions for Coursecontent model.
 */
class CoursecontentController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Coursecontent models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Coursecontent::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Coursecontent model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Coursecontent model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Coursecontent();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['course/view', 'id' => $model->course_id]);
        }
            
        $model->course_id = $id;
        return $this->render('create', [
            'model' => $model, 'id' => $id,
        ]);
    }

    /**
     * Updates an existing Coursecontent model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['course/view', 'id' => $model->course_id]);
        }

        return $this->render('update', [
            'model' => $model, 'id' =>$id,
        ]);
    }

    /**
     * Deletes an existing Coursecontent model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Coursecontent model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Coursecontent the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Coursecontent::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

algobox_admin/views/course/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Course */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="course-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'course_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'active')->dropDownList(['1'=>'Yes', '0'=>'No']); ?>  


    <?php // $form->field($model, 'lastupdate')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

algobox_admin/views/course/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Course */

$this->title = 'Create Course';
$this->params['breadcrumbs'][] = ['label' => 'Courses', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="course-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

algobox_admin/views/course/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Courses';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="course-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Course', ['create'], ['class' => 'btn btn-success']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'course_id',
            //'course_name',
            
            ['attribute' => 'course_name', 
             'headerOptions' => ['width' => '200px'],
             'format' => 'raw', 
             'value' => function ($model) {
                return Html::a($model->course_name,['course/view', 'id' => $model->course_id]);
            }],
            
            'description',
            ['attribute' => 'active',
            'filter'=> ['1'=>'Yes','0'=>'No'],
            'value' => function ($model, $key, $index, $column) {return $model->isActive;},
            'contentOptions' => function ($model, $key, $index, $column) { 
               return $model->active == 1 ? ['style' => 'color:green', 'class' => 'text-center'] : ['style' => 'color:red', 'class' => 'text-center']; 
           }],
            'lastupdate',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

algobox_admin/views/course/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Course */

$this->title = 'Update Course: ' . $model->course_id;
$this->params['breadcrumbs'][] = ['label' => 'Courses', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->course_id, 'url' => ['view', 'id' => $model->course_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="course-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

algobox_admin/views/course/view.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Course */

$this->title = $model->course_name;
$this->params['breadcrumbs'][] = ['label' => 'Courses', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="course-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('<< Back', ['index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Update', ['update', 'id' => $model->course_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->course_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>

        <?= Html::a(Yii::t('app', 'Batch'), ['batch/index','id' => $model->course_id] , ['class' => 'btn btn-info']); ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'course_id',
            'course_name',
            'description',
            ['attribute' => 'active',
            'value' => function ($model) {
                return $model->active ? "Yes" : "No";
            },
            'contentOptions' => ['style' => $model->active ? 'color:green' :'color:red']],
            //'lastupdate',
        ],
    ]) ?>

<h2>Course Content</h2>


<?= Html::a('Create Course content', ['coursecontent/create', 'id' => $model->course_id], ['class' => 'btn btn-success']) ?>


<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        //'coursecontent_id',
        'chapter_name',
        'description',
        'video_link',
        ['attribute' => 'active',
        'value' => function ($model) {
            return $model->active ? "Yes" : "No";
        },
        'contentOptions' => function ($model, $key, $index, $column) { 
            return $model->active ? ['style' => 'color:green'] : ['style' => 'color:red']; 
        }],
        //'seq',
        //'course_id',

        ['class' => 'yii\grid\ActionColumn',
             
             'contentOptions' => ['class' => 'text-center'],
             'buttons' => [
                'view' => function ($url,$model) {
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>',['coursecontent/view', 'id' => $model->coursecontent_id]);
                },
                'update' => function ($url,$model) {
                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>',['coursecontent/update', 'id' => $model->coursecontent_id]);
                },
                'delete' => function ($url,$model) {
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>',['coursecontent/delete', 'id' => $model->coursecontent_id],
                        ['data' => [
                            'confirm' => 'Are you sure you want to delete this item?',
                            'method' => 'post',
                        ],
                    ]);
                },
            ]],
    ],
]); ?>





    

</div>